#!/bin/bash

if [ ! $MVN_HOME ]
then
  echo "MVN_HOME not set"
  exit 1
fi

ARGS=$@
PWD=$(pwd)

$MVN_HOME/bin/mvn ${ARGS}
STATUS=$?
PRIORITY=0

if [ $STATUS -eq 0 ]
then
	VSTATUS=SUCCEEDED
else
	VSTATUS=FAILED
  PRIORITY=2
fi

growlnotify /p:$PRIORITY /s:true /t:"Maven task ${VSTATUS}" "Path: ${PWD}\nmvn ${ARGS}"
exit $STATUS
